name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CC: riscv-none-elf-gcc

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check
          - command: clippy
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src, rustfmt, clippy
      - name: Setup RISCV32 toolchain
        run: |
          RISC_V_GCC_VERSION="14.2.0-3"
          RISC_V_GCC_URL="https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v${RISC_V_GCC_VERSION}/xpack-riscv-none-elf-gcc-${RISC_V_GCC_VERSION}-linux-x64.tar.gz"

          curl -LO "$RISC_V_GCC_URL"
          tar -xzf xpack-riscv-none-elf-gcc-${RISC_V_GCC_VERSION}-linux-x64.tar.gz
          echo "$(pwd)/xpack-riscv-none-elf-gcc-${RISC_V_GCC_VERSION}/bin" >> $GITHUB_PATH

      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
